#baseURL = 'https://circleinaspiral.com/'
languageCode = 'en-us'
title = "Circle in a Spiral"
theme = 'ananke'
resourceDir = "../resources"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/jasondchambers"
[[params.ananke_socials]]
name = "github"
url = "https://github.com/jasondchambers"
