name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update Git submodules - ie. themes
      run: git submodule update --init --recursive
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag www-jasonsblog:$(date +%s)
