name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v1

    - name: Update Git submodules - ie. themes
      run: git submodule update --init --recursive

    - name: Log in to GitHub Packages Docker registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag www-jasonsblog:$(date +%s)
