name: Docker Image CI for GHCR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: www-jasonsblog

jobs:

  build_and_publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write 

    steps:
    - uses: actions/checkout@v4

    - name: Update Git submodules - ie. themes
      run: git submodule update --init --recursive

    - name: Build the push the image 
      run: |
        echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker build . --file Dockerfile --tag ghcr.io/${{github.actor}}/$IMAGE_NAME:latest
        docker push ghcr.io/${{github.actor}}/$IMAGE_NAME:latest
